trigger:
- main
stages:
 - stage: Build
   displayName: Build Docker Image
   jobs:
    - job: Build
      steps:
       - task: PowerShell@2
         inputs:
          targetType: 'inline'
          script: 'Get-ChildItem -Path $(Build.SourcesDirectory)'
       - task: Docker@2
         inputs:
          containerRegistry: 'acrserviceconnection'
          repository: 'testapplication'
          command: 'build'
          Dockerfile: '$(Build.SourcesDirectory)/Azure-DevOps-with-AKS/ADO-BuildandPush-to-ACR/Git-Repofiles/Dockerfile'
